const ShopActionTypes = {
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FALIURE: 'FETCH_COLLECTION_FALIURE',
};

export default ShopActionTypes;
